name: "AI Gateway"
version: "0.0.1.0004"
slug: "ai_gateway"
description: "Centralized Intelligence & Routing for the Personal Secretary Ecosystem"
arch:
  - aarch64
  - amd64
  - armv7
startup: application
boot: auto
map:
  - config:rw
options:
  debug_logging: false
  gemini_api_key: "key1,key2,key3"
  internal_api_key: "change_me_please"
schema:
  debug_logging: bool?
  gemini_api_key: str?
  internal_api_key: password?
ingress: true
ingress_port: 5005
ingress_entry: /
panel_icon: mdi:brain
panel_title: AI Gateway
ports:
  5005/tcp: 5005